module.exports = {
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  plugins: [require("daisyui")],
  theme: {
    extend: {
      colors: {
        brand: {
          background: "#ffffff",
          primary: "#2d033b",
          secondary: "#6366f1",
          tertiary: "#14b8a6",
          accent: "#65a30d",
          highlight: "#ff1fae",
          text: "#6b6375",
        },
        "page-background": "#ffffff",
        "text-primary": "#2d033b",
        "text-secondary": "#6b6375",
        "surface-header": "#ffffff",
        "surface-footer": "#6366f1",
        "surface-emphasis": "#14b8a6",
        "surface-card": "#e0d9e2",
        "action-primary": "#65a30d",
        "action-secondary": "#6366f1",
        "link": "#ff1fae",
        "focus": "#2d033b",
        "border-subtle": "#6b6375",
        "border-emphasis": "#14b8a6",
      },
      fontFamily: {
        sans: ['"Trebuchet MS"', '"Segoe UI"', "sans-serif"],
        heading: ['"Trebuchet MS"', '"Segoe UI"', "sans-serif"],
        mono: ["Consolas", "Monaco", '"Courier New"', "monospace"],
      },
      fontSize: {
        body: ["1rem", { lineHeight: "1.6" }],
        supporting: ["0.875rem", { lineHeight: "1.4" }],
        "link-size": ["1.0625rem", { lineHeight: "1.5" }],
        "project-title": ["1.25rem", { lineHeight: "1.25" }],
        "section-title": ["1.75rem", { lineHeight: "1.2" }],
        "page-title": ["2.5rem", { lineHeight: "1.1" }],
        "hero-title": ["3.5rem", { lineHeight: "1.05" }],
      },
      boxShadow: {
        soft: "0 4px 24px rgba(0, 0, 0, 0.08)",
      },
    },
  },
  safelist: [
    "bg-white",
    "rounded-2xl",
    "mx-auto",
    "my-4",
    "px-6",
    "py-4",
    "max-w-3xl",
    "min-h-[80vh]",
    "shadow-lg",
    "flex",
    "flex-col",
    "border-4",
    "border-green-400",
    "flex-1",
  ],
};
